# Generated by Django 4.2.3 on 2023-07-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_driveruser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='api_customuser',
        ),
        migrations.AlterModelTable(
            name='driveruser',
            table='api_driveruser',
        ),
    ]
